#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: f032afc
#
Name     : R-gdata
Version  : 3.0.0
Release  : 53
URL      : https://cran.r-project.org/src/contrib/gdata_3.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gdata_3.0.0.tar.gz
Summary  : Various R Programming Tools for Data Manipulation
Group    : Development/Tools
License  : GPL-2.0
Requires: R-gtools
BuildRequires : R-gtools
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
medical unit conversions, combining objects, character vector operations,
  factor manipulation, obtaining information about R objects, generating
  fixed-width format files, extracting components of date & time objects,
  operations on columns of data frames, matrix operations, operations on
  vectors, operations on data frames, value of last evaluated expression, and a
  resample() wrapper for sample() that ensures consistent behavior for both
  scalar and vector arguments.

%prep
%setup -q -n gdata
pushd ..
cp -a gdata buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697560171

%install
export SOURCE_DATE_EPOCH=1697560171
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gdata/DESCRIPTION
/usr/lib64/R/library/gdata/INDEX
/usr/lib64/R/library/gdata/Meta/Rd.rds
/usr/lib64/R/library/gdata/Meta/data.rds
/usr/lib64/R/library/gdata/Meta/features.rds
/usr/lib64/R/library/gdata/Meta/hsearch.rds
/usr/lib64/R/library/gdata/Meta/links.rds
/usr/lib64/R/library/gdata/Meta/nsInfo.rds
/usr/lib64/R/library/gdata/Meta/package.rds
/usr/lib64/R/library/gdata/Meta/vignette.rds
/usr/lib64/R/library/gdata/NAMESPACE
/usr/lib64/R/library/gdata/NEWS
/usr/lib64/R/library/gdata/R/gdata
/usr/lib64/R/library/gdata/R/gdata.rdb
/usr/lib64/R/library/gdata/R/gdata.rdx
/usr/lib64/R/library/gdata/data/MedUnits.rda
/usr/lib64/R/library/gdata/doc/index.html
/usr/lib64/R/library/gdata/doc/mapLevels.R
/usr/lib64/R/library/gdata/doc/mapLevels.Rnw
/usr/lib64/R/library/gdata/doc/mapLevels.pdf
/usr/lib64/R/library/gdata/doc/unknown.R
/usr/lib64/R/library/gdata/doc/unknown.Rnw
/usr/lib64/R/library/gdata/doc/unknown.pdf
/usr/lib64/R/library/gdata/help/AnIndex
/usr/lib64/R/library/gdata/help/aliases.rds
/usr/lib64/R/library/gdata/help/gdata.rdb
/usr/lib64/R/library/gdata/help/gdata.rdx
/usr/lib64/R/library/gdata/help/paths.rds
/usr/lib64/R/library/gdata/html/00Index.html
/usr/lib64/R/library/gdata/html/R.css
/usr/lib64/R/library/gdata/tests/runRUnitTests.R
/usr/lib64/R/library/gdata/tests/test.humanReadable.R
/usr/lib64/R/library/gdata/tests/test.humanReadable.Rout.save
/usr/lib64/R/library/gdata/tests/test.reorder.factor.R
/usr/lib64/R/library/gdata/tests/test.reorder.factor.Rout.save
/usr/lib64/R/library/gdata/tests/test.write.fwf.eol.R
/usr/lib64/R/library/gdata/tests/test.write.fwf.eol.Rout.save
/usr/lib64/R/library/gdata/tests/tests.write.fwf.R
/usr/lib64/R/library/gdata/tests/tests.write.fwf.Rout.save
/usr/lib64/R/library/gdata/tests/unitTests/Makefile
/usr/lib64/R/library/gdata/tests/unitTests/runit.bindData.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.cbindX.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.drop.levels.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.getDateTimeParts.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.mapLevels.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.nPairs.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.reorder.factor.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.trim.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.trimSum.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.unknown.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.wideByFactor.R
/usr/lib64/R/library/gdata/tests/unitTests/runit.write.fwf.R
